# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import conexion_pb2 as conexion__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in conexion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BDStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.set = channel.unary_unary(
                '/conexion.BD/set',
                request_serializer=conexion__pb2.Insertar.SerializeToString,
                response_deserializer=conexion__pb2.RespuestaSet.FromString,
                _registered_method=True)
        self.get = channel.unary_unary(
                '/conexion.BD/get',
                request_serializer=conexion__pb2.Consultar.SerializeToString,
                response_deserializer=conexion__pb2.RespuestaGet.FromString,
                _registered_method=True)
        self.getPrefix = channel.unary_unary(
                '/conexion.BD/getPrefix',
                request_serializer=conexion__pb2.Consultar.SerializeToString,
                response_deserializer=conexion__pb2.RespuestaGetPrefix.FromString,
                _registered_method=True)
        self.resetDb = channel.unary_unary(
                '/conexion.BD/resetDb',
                request_serializer=conexion__pb2.RequestResetDb.SerializeToString,
                response_deserializer=conexion__pb2.RespuestaReset.FromString,
                _registered_method=True)


class BDServicer(object):
    """Missing associated documentation comment in .proto file."""

    def set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def resetDb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BDServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'set': grpc.unary_unary_rpc_method_handler(
                    servicer.set,
                    request_deserializer=conexion__pb2.Insertar.FromString,
                    response_serializer=conexion__pb2.RespuestaSet.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=conexion__pb2.Consultar.FromString,
                    response_serializer=conexion__pb2.RespuestaGet.SerializeToString,
            ),
            'getPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.getPrefix,
                    request_deserializer=conexion__pb2.Consultar.FromString,
                    response_serializer=conexion__pb2.RespuestaGetPrefix.SerializeToString,
            ),
            'resetDb': grpc.unary_unary_rpc_method_handler(
                    servicer.resetDb,
                    request_deserializer=conexion__pb2.RequestResetDb.FromString,
                    response_serializer=conexion__pb2.RespuestaReset.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conexion.BD', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conexion.BD', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BD(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conexion.BD/set',
            conexion__pb2.Insertar.SerializeToString,
            conexion__pb2.RespuestaSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conexion.BD/get',
            conexion__pb2.Consultar.SerializeToString,
            conexion__pb2.RespuestaGet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conexion.BD/getPrefix',
            conexion__pb2.Consultar.SerializeToString,
            conexion__pb2.RespuestaGetPrefix.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def resetDb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conexion.BD/resetDb',
            conexion__pb2.RequestResetDb.SerializeToString,
            conexion__pb2.RespuestaReset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
