// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/conexion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestResetDb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResetDb) Reset() {
	*x = RequestResetDb{}
	mi := &file_proto_conexion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResetDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResetDb) ProtoMessage() {}

func (x *RequestResetDb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conexion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResetDb.ProtoReflect.Descriptor instead.
func (*RequestResetDb) Descriptor() ([]byte, []int) {
	return file_proto_conexion_proto_rawDescGZIP(), []int{0}
}

type RespuestaReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        bool                   `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaReset) Reset() {
	*x = RespuestaReset{}
	mi := &file_proto_conexion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaReset) ProtoMessage() {}

func (x *RespuestaReset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conexion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaReset.ProtoReflect.Descriptor instead.
func (*RespuestaReset) Descriptor() ([]byte, []int) {
	return file_proto_conexion_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaReset) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *RespuestaReset) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type RespuestaGetPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        bool                   `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Objetos       []*Objeto              `protobuf:"bytes,3,rep,name=objetos,proto3" json:"objetos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaGetPrefix) Reset() {
	*x = RespuestaGetPrefix{}
	mi := &file_proto_conexion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaGetPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaGetPrefix) ProtoMessage() {}

func (x *RespuestaGetPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conexion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaGetPrefix.ProtoReflect.Descriptor instead.
func (*RespuestaGetPrefix) Descriptor() ([]byte, []int) {
	return file_proto_conexion_proto_rawDescGZIP(), []int{2}
}

func (x *RespuestaGetPrefix) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *RespuestaGetPrefix) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaGetPrefix) GetObjetos() []*Objeto {
	if x != nil {
		return x.Objetos
	}
	return nil
}

type RespuestaGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        bool                   `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Objeto        *Objeto                `protobuf:"bytes,3,opt,name=objeto,proto3" json:"objeto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaGet) Reset() {
	*x = RespuestaGet{}
	mi := &file_proto_conexion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaGet) ProtoMessage() {}

func (x *RespuestaGet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conexion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaGet.ProtoReflect.Descriptor instead.
func (*RespuestaGet) Descriptor() ([]byte, []int) {
	return file_proto_conexion_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaGet) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *RespuestaGet) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaGet) GetObjeto() *Objeto {
	if x != nil {
		return x.Objeto
	}
	return nil
}

type Objeto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clave         string                 `protobuf:"bytes,1,opt,name=clave,proto3" json:"clave,omitempty"`
	Valor         string                 `protobuf:"bytes,2,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Objeto) Reset() {
	*x = Objeto{}
	mi := &file_proto_conexion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Objeto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objeto) ProtoMessage() {}

func (x *Objeto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conexion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objeto.ProtoReflect.Descriptor instead.
func (*Objeto) Descriptor() ([]byte, []int) {
	return file_proto_conexion_proto_rawDescGZIP(), []int{4}
}

func (x *Objeto) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

func (x *Objeto) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

type Consultar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clave         string                 `protobuf:"bytes,1,opt,name=clave,proto3" json:"clave,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consultar) Reset() {
	*x = Consultar{}
	mi := &file_proto_conexion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consultar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consultar) ProtoMessage() {}

func (x *Consultar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conexion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consultar.ProtoReflect.Descriptor instead.
func (*Consultar) Descriptor() ([]byte, []int) {
	return file_proto_conexion_proto_rawDescGZIP(), []int{5}
}

func (x *Consultar) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

type Insertar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clave         string                 `protobuf:"bytes,1,opt,name=clave,proto3" json:"clave,omitempty"`
	Valor         string                 `protobuf:"bytes,2,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Insertar) Reset() {
	*x = Insertar{}
	mi := &file_proto_conexion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insertar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insertar) ProtoMessage() {}

func (x *Insertar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conexion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insertar.ProtoReflect.Descriptor instead.
func (*Insertar) Descriptor() ([]byte, []int) {
	return file_proto_conexion_proto_rawDescGZIP(), []int{6}
}

func (x *Insertar) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

func (x *Insertar) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

type RespuestaSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        bool                   `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaSet) Reset() {
	*x = RespuestaSet{}
	mi := &file_proto_conexion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaSet) ProtoMessage() {}

func (x *RespuestaSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conexion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaSet.ProtoReflect.Descriptor instead.
func (*RespuestaSet) Descriptor() ([]byte, []int) {
	return file_proto_conexion_proto_rawDescGZIP(), []int{7}
}

func (x *RespuestaSet) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *RespuestaSet) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_conexion_proto protoreflect.FileDescriptor

const file_proto_conexion_proto_rawDesc = "" +
	"\n" +
	"\x14proto/conexion.proto\x12\bconexion\"\x10\n" +
	"\x0eRequestResetDb\"B\n" +
	"\x0eRespuestaReset\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\bR\x06estado\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"r\n" +
	"\x12RespuestaGetPrefix\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\bR\x06estado\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12*\n" +
	"\aobjetos\x18\x03 \x03(\v2\x10.conexion.ObjetoR\aobjetos\"j\n" +
	"\fRespuestaGet\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\bR\x06estado\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12(\n" +
	"\x06objeto\x18\x03 \x01(\v2\x10.conexion.ObjetoR\x06objeto\"4\n" +
	"\x06Objeto\x12\x14\n" +
	"\x05clave\x18\x01 \x01(\tR\x05clave\x12\x14\n" +
	"\x05valor\x18\x02 \x01(\tR\x05valor\"!\n" +
	"\tConsultar\x12\x14\n" +
	"\x05clave\x18\x01 \x01(\tR\x05clave\"6\n" +
	"\bInsertar\x12\x14\n" +
	"\x05clave\x18\x01 \x01(\tR\x05clave\x12\x14\n" +
	"\x05valor\x18\x02 \x01(\tR\x05valor\"@\n" +
	"\fRespuestaSet\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\bR\x06estado\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2\xea\x01\n" +
	"\x02BD\x121\n" +
	"\x03set\x12\x12.conexion.Insertar\x1a\x16.conexion.RespuestaSet\x122\n" +
	"\x03get\x12\x13.conexion.Consultar\x1a\x16.conexion.RespuestaGet\x12>\n" +
	"\tgetPrefix\x12\x13.conexion.Consultar\x1a\x1c.conexion.RespuestaGetPrefix\x12=\n" +
	"\aresetDb\x12\x18.conexion.RequestResetDb\x1a\x18.conexion.RespuestaResetB;Z9github.com/yormanbalanD/bd-clave-valor-distribuidos/protob\x06proto3"

var (
	file_proto_conexion_proto_rawDescOnce sync.Once
	file_proto_conexion_proto_rawDescData []byte
)

func file_proto_conexion_proto_rawDescGZIP() []byte {
	file_proto_conexion_proto_rawDescOnce.Do(func() {
		file_proto_conexion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_conexion_proto_rawDesc), len(file_proto_conexion_proto_rawDesc)))
	})
	return file_proto_conexion_proto_rawDescData
}

var file_proto_conexion_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_conexion_proto_goTypes = []any{
	(*RequestResetDb)(nil),     // 0: conexion.RequestResetDb
	(*RespuestaReset)(nil),     // 1: conexion.RespuestaReset
	(*RespuestaGetPrefix)(nil), // 2: conexion.RespuestaGetPrefix
	(*RespuestaGet)(nil),       // 3: conexion.RespuestaGet
	(*Objeto)(nil),             // 4: conexion.Objeto
	(*Consultar)(nil),          // 5: conexion.Consultar
	(*Insertar)(nil),           // 6: conexion.Insertar
	(*RespuestaSet)(nil),       // 7: conexion.RespuestaSet
}
var file_proto_conexion_proto_depIdxs = []int32{
	4, // 0: conexion.RespuestaGetPrefix.objetos:type_name -> conexion.Objeto
	4, // 1: conexion.RespuestaGet.objeto:type_name -> conexion.Objeto
	6, // 2: conexion.BD.set:input_type -> conexion.Insertar
	5, // 3: conexion.BD.get:input_type -> conexion.Consultar
	5, // 4: conexion.BD.getPrefix:input_type -> conexion.Consultar
	0, // 5: conexion.BD.resetDb:input_type -> conexion.RequestResetDb
	7, // 6: conexion.BD.set:output_type -> conexion.RespuestaSet
	3, // 7: conexion.BD.get:output_type -> conexion.RespuestaGet
	2, // 8: conexion.BD.getPrefix:output_type -> conexion.RespuestaGetPrefix
	1, // 9: conexion.BD.resetDb:output_type -> conexion.RespuestaReset
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_conexion_proto_init() }
func file_proto_conexion_proto_init() {
	if File_proto_conexion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_conexion_proto_rawDesc), len(file_proto_conexion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_conexion_proto_goTypes,
		DependencyIndexes: file_proto_conexion_proto_depIdxs,
		MessageInfos:      file_proto_conexion_proto_msgTypes,
	}.Build()
	File_proto_conexion_proto = out.File
	file_proto_conexion_proto_goTypes = nil
	file_proto_conexion_proto_depIdxs = nil
}
